base_text = input("Please enter your text: ")
base_text = base_text.replace("l", "w")
base_text = base_text.replace("L", "W")
base_text = base_text.replace("R", "W")
base_text = base_text.replace("u", "uwu")
base_text = base_text.replace("U", "uwu")
base_text = base_text.replace("o", "owo")
base_text = base_text.replace("O", "owo")
print(base_text.replace("r", "w")) 
